package com.loanmanagementsystem.loanmanagementsystem.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** JPA entity representing a loan application and its lifecycle data. */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class LoanApplication {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Requested loan amount. */
    private Double amount;

    /** Interest rate assigned after evaluation. */
    private Double interestRate;

    /** Loan duration in months. */
    private Integer tenure;

    /** Current loan state (PENDING, APPROVED, REJECTED). */
    @Enumerated(EnumType.STRING)
    private LoanStatus status;

    /** Timestamp when the application was created. */
    private LocalDateTime createdAt;

    /** Applicant full name. */
    private String fullName;

    /** Monthly income of the applicant. */
    private Double monthlyIncome;

    /** Existing monthly debt obligations. */
    private Double monthlyDebt;

    /** Credit score used for risk assessment. */
    private Integer creditScore;

    /** Employment category of the applicant. */
    private String employmentType;

    /** Purpose of the loan. */
    private String purpose;

    /** Debt-to-income ratio used for eligibility scoring. */
    private Double dti;

    /** Calculated risk score. */
    private Integer riskScore;

    /** Final eligibility decision. */
    private String eligibilityDecision;

    /** Owner of this loan application. */
    @ManyToOne
    private User user;
}
