package com.loanmanagementsystem.loanmanagementsystem.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** JPA entity representing an authenticated application user. */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique username used for login. */
    @Column(unique = true, nullable = false)
    private String username;

    /** Encrypted password hash. */
    private String password;

    /** Assigned user role. */
    @Enumerated(EnumType.STRING)
    private UserRole role;

    /** Indicates whether the account is active. */
    @Column(nullable = false)
    private boolean active = true;
}
